//! Surface of revolution — a generatrix curve rotated about an axis.
//! Source: `Geom_SurfaceOfRevolution` (TKG3d).
//!
//! `d0(u, v)`: the point `C(v)` of the generatrix curve is rotated about the
//! axis `A` by angle `u`. `v` runs along the generatrix, `u` is the angular
//! parameter (periodic with period `2π`).

use std::sync::Arc;

use occt_core::gp::{GpAx1, GpDir, GpPnt, GpTrsf, GpVec};

use crate::curve::Curve;
use crate::Surface;

/// A surface generated by rotating a curve about an axis.
///
/// `d0(u, v) = R(A, u) · C(v)` where `C` is the generatrix and `R` is the
/// rotation about axis `A` by angle `u`.
pub struct GeomSurfaceOfRevolution {
    generatrix: Arc<dyn Curve>,
    axis: GpAx1,
    v_first: f64,
    v_last: f64,
}

impl GeomSurfaceOfRevolution {
    /// Build from a generatrix curve and the axis of rotation.
    pub fn new(generatrix: Arc<dyn Curve>, axis: GpAx1) -> Self {
        let (f, l) = (generatrix.first_parameter(), generatrix.last_parameter());
        Self {
            generatrix,
            axis,
            v_first: if f.is_finite() { f } else { 0.0 },
            v_last: if l.is_finite() { l } else { 1.0 },
        }
    }

    /// Rotate the point `p` about the axis by angle `u` (radians).
    fn rotate_about_axis(&self, p: &GpPnt, u: f64) -> GpPnt {
        let loc = self.axis.location();
        let dir = GpVec::from_xyz(&self.axis.direction().xyz());
        let rel = GpVec::from_pnts(&loc, p);
        // Decompose into along-axis and perpendicular components.
        let along = dir.multiplied_scalar(rel.dot(&dir));
        let perp = rel.subtracted(&along);
        let (su, cu) = u.sin_cos();
        // Rotate the perpendicular component in the plane normal to the axis.
        let d = dir.xyz();
        let rot_perp = GpVec::new(
            perp.x() * cu + (d.y() * perp.z() - d.z() * perp.y()) * su,
            perp.y() * cu + (d.z() * perp.x() - d.x() * perp.z()) * su,
            perp.z() * cu + (d.x() * perp.y() - d.y() * perp.x()) * su,
        );
        let rotated = loc.coord.added(&along.coord).added(&rot_perp.coord);
        GpPnt::from_xyz(&rotated)
    }

    /// The generatrix curve (read-only).
    pub fn generatrix(&self) -> &dyn Curve {
        self.generatrix.as_ref()
    }

    /// The axis of rotation.
    pub fn axis(&self) -> GpAx1 {
        self.axis
    }
}

impl crate::Surface for GeomSurfaceOfRevolution {
    fn d0(&self, u: f64, v: f64) -> GpPnt {
        let c = self.generatrix.d0(v);
        self.rotate_about_axis(&c, u)
    }

    fn d1(&self, u: f64, v: f64) -> (GpPnt, GpVec, GpVec) {
        // Numeric partials (the port has no analytic d² for curves/surfaces).
        let h = 1e-6;
        let p = self.d0(u, v);
        let du = self.d0(u + h, v);
        let dv = self.d0(u, v + h);
        let su = GpVec::from_pnts(&p, &du).divided(h);
        let sv = GpVec::from_pnts(&p, &dv).divided(h);
        (p, su, sv)
    }

    fn u_range(&self) -> (f64, f64) {
        (0.0, 2.0 * std::f64::consts::PI)
    }

    fn v_range(&self) -> (f64, f64) {
        (self.v_first, self.v_last)
    }

    fn is_u_periodic(&self) -> bool {
        true
    }

    fn is_v_periodic(&self) -> bool {
        false
    }

    fn continuity(&self) -> u8 {
        // The surface is C1 unless the generatrix has cusps.
        1
    }

    fn transform(&mut self, t: &GpTrsf) {
        // Arc<dyn Curve> is not mutable: clone a fresh Box, transform it, and
        // re-own as Arc (a transformed copy is exact for linear transforms).
        let mut gen = self.generatrix.clone_dyn();
        gen.transform(t);
        self.generatrix = Arc::from(gen);
        // Rebuild the axis under `t`: transform the location point and the
        // direction vector (GpAx1 has no `transformed` in this port).
        let loc = self.axis.location().transformed(t);
        let mut d = *self.axis.direction().xyz();
        t.transforms_xyz(&mut d);
        let dir = GpDir::from_xyz(&d).unwrap_or_else(|_| *self.axis.direction());
        self.axis = GpAx1::new(loc, dir);
    }

    fn clone_dyn(&self) -> Box<dyn crate::Surface> {
        Box::new(GeomSurfaceOfRevolution {
            generatrix: Arc::from(self.generatrix.clone_dyn()),
            axis: self.axis,
            v_first: self.v_first,
            v_last: self.v_last,
        })
    }
}

// Helper for tests: a straight generatrix rotated about the z-axis produces a
// cone/cylinder-like surface.
#[cfg(test)]
mod tests {
    use super::*;
    use crate::GeomLine;
    use occt_core::gp::{GpAx1, GpDir, GpLin, GpPnt};

    fn z_axis() -> GpAx1 {
        GpAx1::new(GpPnt::new(0.0, 0.0, 0.0), GpDir::new(0.0, 0.0, 1.0).unwrap())
    }

    #[test]
    fn line_generatrix_makes_cylinder() {
        // Generatrix x = 2 (constant), y = z = 0 → rotating about z makes a
        // cylinder of radius 2.
        let gen = GeomLine::new(GpLin::from_pnt_dir(
            GpPnt::new(2.0, 0.0, 0.0),
            GpDir::new(0.0, 0.0, 1.0).unwrap(),
        ));
        let s = GeomSurfaceOfRevolution::new(Arc::new(gen), z_axis());
        let p = s.d0(0.0, 0.0);
        assert!((p.x() - 2.0).abs() < 1e-12 && p.y().abs() < 1e-12);
        // Rotating 90° about z sends (2,0) to (0,2).
        let q = s.d0(std::f64::consts::PI / 2.0, 0.0);
        assert!(q.x().abs() < 1e-9 && (q.y() - 2.0).abs() < 1e-9);
        // v moves along z.
        let r = s.d0(0.0, 1.0);
        assert!((r.z() - 1.0).abs() < 1e-9);
        assert!(s.is_u_periodic());
        let (u0, u1) = s.u_range();
        assert!((u0 - 0.0).abs() < 1e-12 && (u1 - 2.0 * std::f64::consts::PI).abs() < 1e-12);
    }

    #[test]
    fn d1_is_finite() {
        let gen = GeomLine::new(GpLin::from_pnt_dir(
            GpPnt::new(1.0, 0.0, 0.0),
            GpDir::new(0.0, 0.0, 1.0).unwrap(),
        ));
        let s = GeomSurfaceOfRevolution::new(Arc::new(gen), z_axis());
        let (p, su, sv) = s.d1(0.5, 0.5);
        assert!(p.z() > -0.1);
        assert!(su.x().abs() > 0.1, "u-partial tangent {su:?}");
        assert!(sv.z().abs() > 0.1, "v-partial tangent {sv:?}");
    }
}
