//! Surface of revolution — a generatrix curve rotated about an axis.
//! Source: `Geom_SurfaceOfRevolution` (TKG3d).
//!
//! `d0(u, v)`: the point `C(v)` of the generatrix curve is rotated about the
//! axis `A` by angle `u`. `v` runs along the generatrix, `u` is the angular
//! parameter (periodic with period `2π`).

use std::sync::Arc;

use occt_core::gp::{GpAx1, GpAx2, GpCirc, GpDir, GpLin, GpPnt, GpTrsf, GpVec};
use occt_core::precision::{RESOLUTION, SQUARE_CONFUSION};

use crate::curve::Curve;
use crate::GeomCircle;
use crate::Surface;

/// A surface generated by rotating a curve about an axis.
///
/// `d0(u, v) = R(A, u) · C(v)` where `C` is the generatrix and `R` is the
/// rotation about axis `A` by angle `u`.
pub struct GeomSurfaceOfRevolution {
    generatrix: Arc<dyn Curve>,
    axis: GpAx1,
    v_first: f64,
    v_last: f64,
}

impl GeomSurfaceOfRevolution {
    /// Build from a generatrix curve and the axis of rotation.
    pub fn new(generatrix: Arc<dyn Curve>, axis: GpAx1) -> Self {
        let (f, l) = (generatrix.first_parameter(), generatrix.last_parameter());
        Self {
            generatrix,
            axis,
            v_first: if f.is_finite() { f } else { 0.0 },
            v_last: if l.is_finite() { l } else { 1.0 },
        }
    }

    /// Rotate the point `p` about the axis by angle `u` (radians).
    fn rotate_about_axis(&self, p: &GpPnt, u: f64) -> GpPnt {
        let loc = self.axis.location();
        let dir = GpVec::from_xyz(&self.axis.direction().xyz());
        let rel = GpVec::from_pnts(&loc, p);
        // Decompose into along-axis and perpendicular components.
        let along = dir.multiplied_scalar(rel.dot(&dir));
        let perp = rel.subtracted(&along);
        let (su, cu) = u.sin_cos();
        // Rotate the perpendicular component in the plane normal to the axis.
        let d = dir.xyz();
        let rot_perp = GpVec::new(
            perp.x() * cu + (d.y() * perp.z() - d.z() * perp.y()) * su,
            perp.y() * cu + (d.z() * perp.x() - d.x() * perp.z()) * su,
            perp.z() * cu + (d.x() * perp.y() - d.y() * perp.x()) * su,
        );
        let rotated = loc.coord.added(&along.coord).added(&rot_perp.coord);
        GpPnt::from_xyz(&rotated)
    }

    /// The generatrix curve (read-only).
    pub fn generatrix(&self) -> &dyn Curve {
        self.generatrix.as_ref()
    }

    /// The axis of rotation.
    pub fn axis(&self) -> GpAx1 {
        self.axis
    }

    /// `Geom_SurfaceOfRevolution::UIso` (`Geom_SurfaceOfRevolution.cxx:372-379`).
    pub fn u_iso(&self, u: f64) -> Arc<dyn Curve> {
        let mut t = GpTrsf::identity();
        let _ = t.set_rotation_ax1(&self.axis, u);
        Arc::from(self.generatrix.transformed(&t))
    }

    /// `Geom_RevolutionUtils::CalculateDN` (`Geom_RevolutionUtils.pxx:222-265`).
    fn calculate_dn(curve_pt_or_dn: &GpVec, u: f64, axis: &GpAx1, der_u: i32) -> GpVec {
        let mut rotation = GpTrsf::identity();
        let _ = rotation.set_rotation_ax1(axis, u);
        let mut result = if der_u == 0 {
            *curve_pt_or_dn
        } else {
            let dir = axis.direction().xyz();
            let xyz = curve_pt_or_dn.xyz();
            match der_u % 4 {
                1 => GpVec::from_xyz(&dir.crossed(xyz)),
                2 => {
                    let proj = dir.multiplied(dir.dot(xyz));
                    GpVec::from_xyz(&proj.subtracted(xyz))
                }
                3 => GpVec::from_xyz(&dir.crossed(xyz)).multiplied_scalar(-1.0),
                _ => {
                    let proj = dir.multiplied(dir.dot(xyz));
                    GpVec::from_xyz(&xyz.subtracted(&proj))
                }
            }
        };
        rotation.transforms_xyz_dir(&mut result.coord);
        result
    }

    /// `Geom_SurfaceOfRevolution::EvalDN` (`Geom_SurfaceOfRevolution.cxx:331-360`).
    /// Illegal Nu/Nv returns zero instead of throw. Eval-rep is empty.
    pub fn eval_dn_rev(&self, u: f64, v: f64, nu: i32, nv: i32) -> GpVec {
        if nu + nv < 1 || nu < 0 || nv < 0 {
            return GpVec::zero();
        }
        let loc = self.axis.location();
        let curve_pt_or_dn = if nu == 0 {
            self.generatrix.eval_dn(v, nv)
        } else if nv == 0 {
            let d0 = self.generatrix.d0(v);
            GpVec::new(d0.x() - loc.x(), d0.y() - loc.y(), d0.z() - loc.z())
        } else {
            self.generatrix.eval_dn(v, nv)
        };
        Self::calculate_dn(&curve_pt_or_dn, u, &self.axis, nu)
    }

    fn transform_vec(t: &GpTrsf, v: &GpVec) -> GpVec {
        let mut xyz = v.coord;
        t.transforms_xyz_dir(&mut xyz);
        GpVec::from_xyz(&xyz)
    }

    /// `Geom_RevolutionUtils::CalculateD1` (`Geom_RevolutionUtils.pxx:62-88`).
    fn calculate_d1(curve_pt: &GpPnt, curve_d1: &GpVec, u: f64, axis: &GpAx1) -> (GpPnt, GpVec, GpVec) {
        let cq = curve_pt.coord.subtracted(&axis.location().coord);
        let dir = axis.direction().xyz();
        let mut d1u = GpVec::from_xyz(&dir.crossed(&cq));
        if d1u.square_magnitude() < SQUARE_CONFUSION {
            d1u = GpVec::zero();
        }
        let mut rotation = GpTrsf::identity();
        let _ = rotation.set_rotation_ax1(axis, u);
        let p = curve_pt.transformed(&rotation);
        d1u = Self::transform_vec(&rotation, &d1u);
        let d1v = Self::transform_vec(&rotation, curve_d1);
        (p, d1u, d1v)
    }

    /// `Geom_RevolutionUtils::CalculateD2` (`Geom_RevolutionUtils.pxx:103-140`).
    fn calculate_d2(
        curve_pt: &GpPnt,
        curve_d1: &GpVec,
        curve_d2: &GpVec,
        u: f64,
        axis: &GpAx1,
    ) -> (GpPnt, GpVec, GpVec, GpVec, GpVec, GpVec) {
        let cq = curve_pt.coord.subtracted(&axis.location().coord);
        let dir = axis.direction().xyz();
        let mut d1u = GpVec::from_xyz(&dir.crossed(&cq));
        if d1u.square_magnitude() < SQUARE_CONFUSION {
            d1u = GpVec::zero();
        }
        let d2u = GpVec::from_xyz(&dir.multiplied(dir.dot(&cq)).subtracted(&cq));
        let d2uv = GpVec::from_xyz(&dir.crossed(curve_d1.xyz()));
        let mut rotation = GpTrsf::identity();
        let _ = rotation.set_rotation_ax1(axis, u);
        let p = curve_pt.transformed(&rotation);
        d1u = Self::transform_vec(&rotation, &d1u);
        let d1v = Self::transform_vec(&rotation, curve_d1);
        let d2u = Self::transform_vec(&rotation, &d2u);
        let d2v = Self::transform_vec(&rotation, curve_d2);
        let d2uv = Self::transform_vec(&rotation, &d2uv);
        (p, d1u, d1v, d2u, d2v, d2uv)
    }

    /// `Geom_SurfaceOfRevolution::VIso` (`Geom_SurfaceOfRevolution.cxx:383-415`).
    pub fn v_iso(&self, v: f64) -> Arc<dyn Curve> {
        let loc = self.axis.location();
        let direction = *self.axis.direction();
        let pc = self.generatrix.d0(v);
        let l1 = GpLin::from_pnt_dir(*loc, direction);
        let rad = l1.distance(&pc);
        let rep = if rad > RESOLUTION {
            let p = pc.coord;
            let c_xyz = loc.coord.added(
                &direction
                    .xyz()
                    .multiplied(p.subtracted(&loc.coord).dot(direction.xyz())),
            );
            let radial = p.subtracted(&c_xyz);
            let c = GpPnt::from_xyz(&c_xyz);
            if radial.modulus() > RESOLUTION {
                let d = GpDir::from_xyz(&radial).unwrap_or(direction);
                GpAx2::new(c, direction, d).unwrap_or_else(|_| GpAx2::from_axis(c, direction))
            } else {
                GpAx2::from_axis(c, direction)
            }
        } else {
            GpAx2::from_axis(pc, direction)
        };
        Arc::new(GeomCircle::new(GpCirc::new(rep, rad)))
    }
}

impl crate::Surface for GeomSurfaceOfRevolution {
    fn d0(&self, u: f64, v: f64) -> GpPnt {
        let c = self.generatrix.d0(v);
        self.rotate_about_axis(&c, u)
    }

    fn d1(&self, u: f64, v: f64) -> (GpPnt, GpVec, GpVec) {
        let (p, d1) = self.generatrix.d1(v);
        Self::calculate_d1(&p, &d1, u, &self.axis)
    }

    fn d2(&self, u: f64, v: f64) -> (GpPnt, GpVec, GpVec, GpVec, GpVec, GpVec) {
        let (p, d1, d2) = self.generatrix.d2(v);
        Self::calculate_d2(&p, &d1, &d2, u, &self.axis)
    }

    fn u_range(&self) -> (f64, f64) {
        (0.0, 2.0 * std::f64::consts::PI)
    }

    fn v_range(&self) -> (f64, f64) {
        (self.v_first, self.v_last)
    }

    fn is_u_periodic(&self) -> bool {
        true
    }

    fn is_surface_of_revolution(&self) -> bool {
        true
    }

    fn revolution_basis_curve(&self) -> Option<Arc<dyn Curve>> {
        Some(self.generatrix.clone())
    }

    fn revolution_axis(&self) -> Option<occt_core::gp::GpAx1> {
        Some(self.axis())
    }

    /// `GeomAdaptor_SurfaceOfRevolution::UResolution` / `VResolution`
    /// (`cxx:356-366`) and `GeomAdaptor_Surface::VResolution` Revolution arm
    /// (`cxx:1906-1908`). U is `Precision::Parametric`; V follows the basis.
    fn uv_resolution(&self, r3d: f64) -> Option<(f64, f64)> {
        let ru = r3d * occt_core::precision::PCONFUSION / occt_core::precision::CONFUSION;
        let rv = self.generatrix.resolution(r3d);
        Some((ru, rv))
    }

    fn is_v_periodic(&self) -> bool {
        false
    }

    fn continuity(&self) -> u8 {
        // The surface is C1 unless the generatrix has cusps.
        1
    }

    fn transform(&mut self, t: &GpTrsf) {
        // Arc<dyn Curve> is not mutable: clone a fresh Box, transform it, and
        // re-own as Arc (a transformed copy is exact for linear transforms).
        let mut gen = self.generatrix.clone_dyn();
        gen.transform(t);
        self.generatrix = Arc::from(gen);
        // Rebuild the axis under `t`: transform the location point and the
        // direction vector (GpAx1 has no `transformed` in this port).
        let loc = self.axis.location().transformed(t);
        let mut d = *self.axis.direction().xyz();
        t.transforms_xyz(&mut d);
        let dir = GpDir::from_xyz(&d).unwrap_or_else(|_| *self.axis.direction());
        self.axis = GpAx1::new(loc, dir);
    }

    fn clone_dyn(&self) -> Box<dyn crate::Surface> {
        Box::new(GeomSurfaceOfRevolution {
            generatrix: Arc::from(self.generatrix.clone_dyn()),
            axis: self.axis,
            v_first: self.v_first,
            v_last: self.v_last,
        })
    }

    fn u_iso_curve(&self, u: f64) -> Option<Arc<dyn Curve>> {
        Some(self.u_iso(u))
    }

    fn v_iso_curve(&self, v: f64) -> Option<Arc<dyn Curve>> {
        Some(self.v_iso(v))
    }

    fn eval_dn(&self, u: f64, v: f64, nu: i32, nv: i32) -> GpVec {
        self.eval_dn_rev(u, v, nu, nv)
    }
}

// Helper for tests: a straight generatrix rotated about the z-axis produces a
// cone/cylinder-like surface.
#[cfg(test)]
mod tests {
    use super::*;
    use crate::GeomLine;
    use occt_core::gp::{GpAx1, GpDir, GpLin, GpPnt};

    fn z_axis() -> GpAx1 {
        GpAx1::new(GpPnt::new(0.0, 0.0, 0.0), GpDir::new(0.0, 0.0, 1.0).unwrap())
    }

    #[test]
    fn line_generatrix_makes_cylinder() {
        // Generatrix x = 2 (constant), y = z = 0 → rotating about z makes a
        // cylinder of radius 2.
        let gen = GeomLine::new(GpLin::from_pnt_dir(
            GpPnt::new(2.0, 0.0, 0.0),
            GpDir::new(0.0, 0.0, 1.0).unwrap(),
        ));
        let s = GeomSurfaceOfRevolution::new(Arc::new(gen), z_axis());
        let p = s.d0(0.0, 0.0);
        assert!((p.x() - 2.0).abs() < 1e-12 && p.y().abs() < 1e-12);
        // Rotating 90° about z sends (2,0) to (0,2).
        let q = s.d0(std::f64::consts::PI / 2.0, 0.0);
        assert!(q.x().abs() < 1e-9 && (q.y() - 2.0).abs() < 1e-9);
        // v moves along z.
        let r = s.d0(0.0, 1.0);
        assert!((r.z() - 1.0).abs() < 1e-9);
        assert!(s.is_u_periodic());
        let (u0, u1) = s.u_range();
        assert!((u0 - 0.0).abs() < 1e-12 && (u1 - 2.0 * std::f64::consts::PI).abs() < 1e-12);
    }

    #[test]
    fn d1_is_finite() {
        let gen = GeomLine::new(GpLin::from_pnt_dir(
            GpPnt::new(1.0, 0.0, 0.0),
            GpDir::new(0.0, 0.0, 1.0).unwrap(),
        ));
        let s = GeomSurfaceOfRevolution::new(Arc::new(gen), z_axis());
        let (p, su, sv) = s.d1(0.5, 0.5);
        assert!(p.z() > -0.1);
        assert!(su.x().abs() > 0.1, "u-partial tangent {su:?}");
        assert!(sv.z().abs() > 0.1, "v-partial tangent {sv:?}");
    }
}
