//! Surface of linear extrusion - a basis curve swept along a fixed direction.
//! Source: `Geom_SurfaceOfLinearExtrusion` (TKG3d).
//!
//! `d0(u, v)`: the point `C(u)` of the basis curve translated by `v` times the
//! unit direction. `u` runs along the basis curve, `v` runs along the extrusion
//! direction and is unbounded (`Geom_SurfaceOfLinearExtrusion.cxx:139-144`).

use std::sync::Arc;

use occt_core::gp::{GpDir, GpLin, GpPnt, GpTrsf, GpVec};

use crate::curve::Curve;
use crate::GeomLine;
use crate::Surface;

/// A surface generated by sweeping a curve along a direction.
///
/// `d0(u, v) = C(u) + v * D` where `C` is the basis curve and `D` the
/// direction of extrusion (stored normalized, like `gp_Dir`).
pub struct GeomSurfaceOfLinearExtrusion {
    basis_curve: Arc<dyn Curve>,
    direction: GpDir,
}

impl GeomSurfaceOfLinearExtrusion {
    /// `Geom_SurfaceOfLinearExtrusion::Geom_SurfaceOfLinearExtrusion`
    /// (`Geom_SurfaceOfLinearExtrusion.cxx:80-86`): store the curve copy, the
    /// direction and `smooth = C->Continuity()`.
    pub fn new(basis_curve: Arc<dyn Curve>, direction: GpDir) -> Self {
        Self {
            basis_curve,
            direction,
        }
    }

    /// `Geom_SweptSurface::BasisCurve` (`Geom_SweptSurface.cxx:40-43`).
    pub fn basis_curve(&self) -> &dyn Curve {
        self.basis_curve.as_ref()
    }

    /// `Geom_SweptSurface::Direction` (`Geom_SweptSurface.cxx:32-35`).
    pub fn direction(&self) -> GpDir {
        self.direction
    }

    /// `Geom_SurfaceOfLinearExtrusion::UIso` (`cxx:275-280`): the line through
    /// `C(U)` along the direction of extrusion.
    pub fn u_iso(&self, u: f64) -> Arc<dyn Curve> {
        Arc::new(GeomLine::new(GpLin::from_pnt_dir(
            self.basis_curve.d0(u),
            self.direction,
        )))
    }

    /// `Geom_SurfaceOfLinearExtrusion::VIso` (`cxx:285-292`): the basis curve
    /// translated by `V * Direction`.
    pub fn v_iso(&self, v: f64) -> Arc<dyn Curve> {
        let shift = GpVec::from_xyz(&self.direction.xyz().multiplied(v));
        Arc::from(self.basis_curve.translated(&shift))
    }

    /// `Geom_ExtrusionUtils::CalculateD0` (`Geom_ExtrusionUtils.pxx:39-46`).
    fn calculate_d0(&self, curve_pt: &GpPnt, v: f64) -> GpPnt {
        GpPnt::from_xyz(&curve_pt.coord.added(&self.direction.xyz().multiplied(v)))
    }
}

impl Surface for GeomSurfaceOfLinearExtrusion {
    /// `Geom_SurfaceOfLinearExtrusion::EvalD0` (`cxx:150-162`).
    fn d0(&self, u: f64, v: f64) -> GpPnt {
        let c = self.basis_curve.d0(u);
        self.calculate_d0(&c, v)
    }

    /// `Geom_SurfaceOfLinearExtrusion::EvalD1` (`cxx:166-182`) through
    /// `Geom_ExtrusionUtils::CalculateD1` (`pxx:55-66`): `D1U = C'(U)`,
    /// `D1V = Direction`.
    fn d1(&self, u: f64, v: f64) -> (GpPnt, GpVec, GpVec) {
        let (p, d1) = self.basis_curve.d1(u);
        (
            self.calculate_d0(&p, v),
            d1,
            GpVec::from_xyz(self.direction.xyz()),
        )
    }

    /// `Geom_SurfaceOfLinearExtrusion::EvalD2` (`cxx:186-210`) through
    /// `Geom_ExtrusionUtils::CalculateD2` (`pxx:81-98`): `D2U = C''(U)`,
    /// `D2V = D2UV = 0`.
    fn d2(&self, u: f64, v: f64) -> (GpPnt, GpVec, GpVec, GpVec, GpVec, GpVec) {
        let (p, d1, d2) = self.basis_curve.d2(u);
        (
            self.calculate_d0(&p, v),
            d1,
            GpVec::from_xyz(self.direction.xyz()),
            d2,
            GpVec::zero(),
            GpVec::zero(),
        )
    }

    /// `Geom_SurfaceOfLinearExtrusion::Bounds` (`cxx:139-144`): U is the basis
    /// curve range, V is infinite in both directions.
    fn u_range(&self) -> (f64, f64) {
        (
            self.basis_curve.first_parameter(),
            self.basis_curve.last_parameter(),
        )
    }

    fn v_range(&self) -> (f64, f64) {
        (f64::NEG_INFINITY, f64::INFINITY)
    }

    /// `Geom_SurfaceOfLinearExtrusion::IsUPeriodic` (`cxx:332-335`).
    fn is_u_periodic(&self) -> bool {
        self.basis_curve.is_periodic()
    }

    /// `Geom_SurfaceOfLinearExtrusion::IsVPeriodic` (`cxx:346-350`).
    fn is_v_periodic(&self) -> bool {
        false
    }

    /// `Geom_SurfaceOfLinearExtrusion::IsUClosed` (`cxx:325-328`) is
    /// `BasisCurve->IsClosed()`. UNPORTED: the `Curve` trait exposes no
    /// `IsClosed` query, so the inherited default (periodic => closed) is kept.
    fn is_u_closed(&self) -> bool {
        self.is_u_periodic()
    }

    /// `STANDARD_TYPE(Geom_SurfaceOfLinearExtrusion)`, the type that
    /// `GeomAdaptor_Surface::load` (`GeomAdaptor_Surface.cxx:468-479`) maps to
    /// `GeomAbs_SurfaceOfExtrusion`.
    fn is_surface_of_linear_extrusion(&self) -> bool {
        true
    }

    /// `GeomAdaptor_SurfaceOfLinearExtrusion::NbUIntervals` (`cxx:159-162`).
    fn nb_u_intervals(&self, continuity: u8) -> i32 {
        self.basis_curve.nb_intervals(continuity)
    }

    /// `GeomAdaptor_SurfaceOfLinearExtrusion::NbVIntervals` (`cxx:166-169`).
    fn nb_v_intervals(&self, _continuity: u8) -> i32 {
        1
    }

    /// `GeomAdaptor_SurfaceOfLinearExtrusion::UIntervals` (`cxx:173-177`).
    fn u_intervals(&self, continuity: u8) -> Vec<f64> {
        self.basis_curve.parameter_intervals(continuity)
    }

    /// `Geom_SurfaceOfLinearExtrusion::UIso` through
    /// `Adaptor3d_Surface::UIso`.
    fn u_iso_curve(&self, u: f64) -> Option<Arc<dyn Curve>> {
        Some(self.u_iso(u))
    }

    /// `Geom_SurfaceOfLinearExtrusion::VIso`.
    fn v_iso_curve(&self, v: f64) -> Option<Arc<dyn Curve>> {
        Some(self.v_iso(v))
    }

    /// `Adaptor3d_Surface::BasisCurve` on `Geom_SurfaceOfLinearExtrusion`.
    fn extrusion_basis_curve(&self) -> Option<Arc<dyn Curve>> {
        Some(self.basis_curve.clone())
    }

    /// `Geom_SweptSurface::Direction` of a linear extrusion.
    fn extrusion_direction(&self) -> Option<GpDir> {
        Some(self.direction)
    }

    /// `GeomAdaptor_SurfaceOfLinearExtrusion::UResolution` / `VResolution`
    /// (`cxx:255-265`) and the `GeomAdaptor_Surface::UResolution` extrusion arm
    /// (`GeomAdaptor_Surface.cxx:1824-1827`) with `VResolution` falling to `R3d`
    /// (`cxx:1928-1933`).
    fn uv_resolution(&self, r3d: f64) -> Option<(f64, f64)> {
        Some((self.basis_curve.resolution(r3d), r3d))
    }

    /// `Geom_SweptSurface::Continuity` (`Geom_SweptSurface.cxx:26-29`):
    /// `smooth = C->Continuity()`.
    fn continuity(&self) -> u8 {
        self.basis_curve.continuity()
    }

    /// `Geom_SurfaceOfLinearExtrusion::Transform` (`cxx:315-319`): transform
    /// the direction and the basis curve.
    fn transform(&mut self, t: &GpTrsf) {
        let mut d = *self.direction.xyz();
        t.transforms_xyz_dir(&mut d);
        self.direction = GpDir::from_xyz(&d).unwrap_or(self.direction);
        let mut basis = self.basis_curve.clone_dyn();
        basis.transform(t);
        self.basis_curve = Arc::from(basis);
    }

    fn clone_dyn(&self) -> Box<dyn crate::Surface> {
        Box::new(GeomSurfaceOfLinearExtrusion {
            basis_curve: Arc::from(self.basis_curve.clone_dyn()),
            direction: self.direction,
        })
    }

    /// `Geom_SurfaceOfLinearExtrusion::EvalDN` (`cxx:245-271`).
    fn eval_dn(&self, u: f64, v: f64, nu: i32, nv: i32) -> GpVec {
        let _ = v;
        if nu + nv < 1 || nu < 0 || nv < 0 {
            return GpVec::zero();
        }
        if nv == 0 {
            return self.basis_curve.eval_dn(u, nu);
        } else if nu == 0 && nv == 1 {
            return GpVec::from_xyz(self.direction.xyz());
        }
        GpVec::zero()
    }
}
